### ISSUE TITLE
Decide on the key features

### ISSUE THREAD

**Issue by antisunshine** [antisunshine/aimo#1]
First steps. Let's draft the project.

- [x] voice guidance?
- [x] very simplistic
- [x] finnish/english/swedish (translations can be tba)
- [x] some mascot guide
- [x] very simple tutorials
- [x] font size options
- [x] live support via video chat/call/text chat
- [x] feedback option
- [x] baseline test

**Comment by AnnaElo** [comment]
I think voice guidance is a good idea, because many elder people can't read small text in the smartphone. Maybe also the font of the text could be re-sizable in the application? And cute mascot would be great!

**Comment by SumiyaC** [comment]
assistance trough chat/call if needed ?
feedback option?-from there we can pick up next topic of our new tutorial
maybe more personalized?-if a person is using our app only for basic banking support we can show the recommendations based on that

**Comment by sadikshya2001** [comment]
Voice guidance is a good idea but if they are in a problem and are in public, it might be a hassle. But to make this idea more practical we can do more research. And like other applications, we will have our help service- and that help may be available in video and in written text so that they can read and watch how to solve the issue.

**Comment by antisunshine** [comment]
I was also thinking about a small skill test, or maybe just a simple questionnaire with the starting tutorial to configure each user tasks suited to their skill level.
